name: Build

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'deploy/*.json'
  workflow_dispatch:

env:
  DOTNET_VERSION: "10.0.x"
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Get previous build number
      id: getPreviousBuild
      shell: bash
      run: |
        PREVIOUS_TAG=$(git for-each-ref --sort=-version:refname --count 1 --format="%(refname:short)" "refs/tags/*")
        echo result=${PREVIOUS_TAG} >> $GITHUB_OUTPUT

    - name: Get current build number
      id: getCurrentBuild
      if: success()
      shell: bash
      env:
        PREVIOUS_BUILD: ${{ steps.getPreviousBuild.outputs.result }}
      run: echo result=$((++PREVIOUS_BUILD)) >> $GITHUB_OUTPUT

    - name: Publish
      run: dotnet publish DuoEntraOidSync/DuoEntraOidSync.csproj -c ${{ env.BUILD_CONFIGURATION }} -o publish /p:Version=${{ steps.getCurrentBuild.outputs.result }}

    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: DuoEntraOidSync
        path: publish

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
      if: ${{ success() && github.ref_name == 'master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''
        custom_tag: ${{ steps.getCurrentBuild.outputs.result }}

    - name: Generate release diff
      if: ${{ success() && github.ref_name == 'master' }}
      shell: bash
      env:
        BEGIN_COMMIT: ${{ steps.getPreviousBuild.outputs.result }}
        END_COMMIT: ${{ steps.getCurrentBuild.outputs.result }}
      run: git fetch --tags --force && git log --pretty=format:"* %s (%h)" ${BEGIN_COMMIT}..${END_COMMIT} > release_notes.md

    - name: Zip publish folder
      run: Compress-Archive -Path "publish\*" -DestinationPath "DuoEntraOidSync.zip"

    - name: Create release
      uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
      if: ${{ success() && github.ref_name == 'master' }}
      with:
        artifacts: DuoEntraOidSync.zip
        allowUpdates: true
        bodyFile: "release_notes.md"
        draft: false
        prerelease: false
        name: Build ${{ steps.getCurrentBuild.outputs.result }} (${{ github.ref_name }})
        tag: ${{ steps.getCurrentBuild.outputs.result }}
        token: ${{ secrets.GITHUB_TOKEN }}
